---
apiVersion: v1
kind: Service
metadata:
  name: book-api
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:129703977775:certificate/06a29e59-576f-45ae-936f-d467939be96b
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    app: book-api
spec:
  selector:
    app: book-api
  ports:
  - protocol: TCP
    port: 443
    name: https
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: book-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
      - name: book-api
        image: truonghongphuoc/book-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 400m
        env:
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: dbname
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: password
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: book-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70